import {
  EMPTY_OPERATOR_COMPANY,
  EMPTY_OPERATOR_PRIVATE,
  type Authorization,
  type Certificate,
  type DocumentRef,
  type Drone,
  type DronePublicSnapshot,
  type Insurance,
  type Operator,
  type Pilot,
  type Plan,
  type Report,
  type Slots,
  type SupportMessage,
  type SupportThread,
} from '@/lib/types/entities';
import { DEMO_ACCOUNTS } from '@/lib/demo/personas';
import { MICHELE_CAFFAGNI_BRANDING as MICHELE } from '@/lib/demo/micheleCaffagni';
import { DEMO_BRANDING } from '@/lib/demo/demoBranding';

const ago = (days: number, hours = 0): string =>
  new Date(Date.now() - days * 86400000 - hours * 3600000).toISOString();

const ahead = (days: number): string =>
  new Date(Date.now() + days * 86400000).toISOString();

const aheadDate = (days: number): string => ahead(days).slice(0, 10);
const agoDate = (days: number): string => ago(days).slice(0, 10);

const emptyAddr = { line1: '', line2: '', city: '', postalCode: '', country: '' };

function acct(uid: string) {
  const a = DEMO_ACCOUNTS.find((x) => x.uid === uid);
  if (!a) throw new Error(`missing demo account ${uid}`);
  return a;
}

function pilotFromAccount(
  uid: string,
  extras: Partial<Pilot> = {},
): Pilot {
  const a = DEMO_ACCOUNTS.find((x) => x.uid === uid)!;
  return {
    userId: uid,
    firstName: a.firstName,
    lastName: a.lastName,
    dateOfBirth: a.dateOfBirth,
    nationality: extras.nationality ?? '',
    email: a.email,
    phone: a.phone,
    address: a.address,
    operatorCode: extras.operatorCode ?? '',
    operatorLicense: extras.operatorLicense ?? '',
    emergencyContact: extras.emergencyContact ?? '',
    createdAt: a.createdAt,
    updatedAt: a.updatedAt,
  };
}

function privateOp(
  id: string,
  userId: string,
  label: string,
  isDefault: boolean,
  details: Partial<Operator['private']>,
): Operator {
  return {
    id,
    userId,
    kind: 'private',
    label,
    isDefault,
    private: { ...EMPTY_OPERATOR_PRIVATE, ...details },
    company: { ...EMPTY_OPERATOR_COMPANY },
    createdAt: ago(40),
    updatedAt: ago(2),
  };
}

function companyOp(
  id: string,
  userId: string,
  label: string,
  isDefault: boolean,
  details: Partial<Operator['company']>,
): Operator {
  return {
    id,
    userId,
    kind: 'company',
    label,
    isDefault,
    private: { ...EMPTY_OPERATOR_PRIVATE },
    company: { ...EMPTY_OPERATOR_COMPANY, ...details },
    createdAt: ago(60),
    updatedAt: ago(3),
  };
}

function drone(partial: Partial<Drone> & Pick<Drone, 'id' | 'userId' | 'slug' | 'status' | 'visibility' | 'verificationStatus' | 'manufacturer' | 'model' | 'classMarking' | 'droneSerialNumber' | 'linkedPilotId' | 'defaultOperatorId' | 'insuranceId' | 'createdAt' | 'updatedAt' | 'publishedAt' | 'lastVerifiedAt'>): Drone {
  return {
    controllerSerialNumber: '',
    activeOperatorId: null,
    activeOperatorUntil: null,
    activeOperatorSetAt: '',
    activeOperatorSetBy: '',
    activeOperatorReason: '',
    dataLockedAt: partial.dataLockedAt ?? (partial.publishedAt || partial.createdAt),
    ...partial,
  };
}

function publicSnap( partial: DronePublicSnapshot): DronePublicSnapshot {
  return partial;
}


export type DemoSeedPayload = {
  pilots: Pilot[];
  operators: Operator[];
  insurances: Insurance[];
  certificates: Certificate[];
  documents: DocumentRef[];
  authorizations: Authorization[];
  drones: Drone[];
  slots: Slots[];
  plans: Plan[];
  reports: Report[];
  publics: DronePublicSnapshot[];
  supportThreads: SupportThread[];
  supportMessages: SupportMessage[];
};

export function buildDemoSeedPayload(): DemoSeedPayload {

    const pilots: Pilot[] = [
    pilotFromAccount('demo-admin', {
      nationality: '',
      operatorCode: '',
      operatorLicense: '',
    }),
    pilotFromAccount('demo-michele', {
      nationality: 'Italian',
      operatorCode: MICHELE.operatorCode,
      operatorLicense: MICHELE.operatorLicense,
      emergencyContact: '+39 348 000 1122',
    }),
    pilotFromAccount('demo-alpine', {
      nationality: 'Italian',
      operatorCode: 'IT-OP-ALP-042',
      operatorLicense: 'IT-STS-2023-1100',
      emergencyContact: '+39 0471 555 211',
    }),
    pilotFromAccount('demo-anna', {
      nationality: 'German',
      operatorCode: 'DE-OP-2024-002',
      operatorLicense: 'DE-A2-2024-8834',
      emergencyContact: '+49 170 9998877',
    }),
    pilotFromAccount('demo-pierre', {
      nationality: 'French',
      operatorCode: '',
      operatorLicense: '',
    }),
    pilotFromAccount('demo-carlos', {
      nationality: 'Spanish',
      operatorCode: 'ES-OP-201-2023',
      operatorLicense: 'ES-STS-2023-7712',
      emergencyContact: '+34 600 111 222',
    }),
  ];

  const operators: Operator[] = [
    privateOp('op-michele-1', 'demo-michele', 'Michele · privato', true, {
      firstName: 'Michele',
      lastName: 'Caffagni',
      dateOfBirth: '1985-03-12',
      email: 'michele@360drone.it',
      phone: '+39 340 123 4567',
      address: acct('demo-michele').address,
    }),
    companyOp('op-michele-2', 'demo-michele', '360° Drone', false, {
      companyName: MICHELE.companyName,
      contactPerson: 'Michele Caffagni',
      vatNumber: '',
      uniqueCompanyNumber: '',
      email: 'info@360drone.it',
      address: acct('demo-michele').address,
    }),
    companyOp('op-alpine-1', 'demo-alpine', 'Alpine Drones SRL', true, {
      companyName: 'Alpine Drones SRL',
      contactPerson: 'Luca Ferrari',
      vatNumber: 'IT02345678901',
      uniqueCompanyNumber: 'REA BZ-123456',
      email: 'ops@alpinedrones.it',
      address: acct('demo-alpine').address,
    }),
    privateOp('op-alpine-2', 'demo-alpine', 'Pilota ospite · Sara', false, {
      firstName: 'Sara',
      lastName: 'Negri',
      dateOfBirth: '1990-01-14',
      email: 'sara.negri@alpinedrones.it',
      phone: '+39 347 888 2211',
      address: acct('demo-alpine').address,
    }),
    companyOp('op-anna-1', 'demo-anna', 'SkyMap GmbH', true, {
      companyName: 'SkyMap GmbH',
      contactPerson: 'Anna Müller',
      vatNumber: 'DE298765432',
      email: 'anna.mueller@skymap.de',
      address: acct('demo-anna').address,
    }),
    companyOp('op-pierre-1', 'demo-pierre', 'AeroPro SARL', true, {
      companyName: 'AeroPro SARL',
      contactPerson: 'Pierre Dupont',
      email: 'pierre.dupont@aeropro.fr',
      address: emptyAddr,
    }),
    companyOp('op-carlos-1', 'demo-carlos', 'DroneVista S.L.', true, {
      companyName: 'DroneVista S.L.',
      contactPerson: 'Carlos García',
      vatNumber: 'ESB12345678',
      email: 'carlos@dronevista.es',
      address: acct('demo-carlos').address,
    }),
  ];

  const insurances: Insurance[] = [
    {
      id: 'ins-michele-1',
      userId: 'demo-michele',
      link: 'drone',
      droneId: 'drn-michele-1',
      droneIds: ['drn-michele-1', 'drn-michele-2'],
      operatorId: null,
      provider: MICHELE.insuranceProvider,
      policyNumber: MICHELE.insurancePolicyNumber,
      holderName: 'Michele Caffagni',
      issueDate: MICHELE.insuranceIssueDate,
      expiryDate: MICHELE.insuranceExpiryDate,
      notes: MICHELE.insuranceNotes,
      pdfUrl: MICHELE.insurancePdfUrl,
      verificationStatus: 'verified',
      createdAt: ago(200),
      updatedAt: ago(10),
      dataLockedAt: ago(190),
    },
    {
      id: 'ins-michele-2',
      userId: 'demo-michele',
      link: 'operator',
      droneId: null,
      droneIds: [],
      operatorId: 'op-michele-2',
      provider: 'Generali',
      policyNumber: 'GEN-UAS-8891',
      holderName: '360° Drone',
      issueDate: agoDate(90),
      expiryDate: aheadDate(20),
      notes: 'Rinnovo entro 3 settimane',
      pdfUrl: '',
      verificationStatus: 'verified',
      createdAt: ago(90),
      updatedAt: ago(4),
      dataLockedAt: ago(85),
    },
    {
      id: 'ins-alpine-1',
      userId: 'demo-alpine',
      link: 'operator',
      droneId: null,
      droneIds: ['drn-alpine-1', 'drn-alpine-2'],
      operatorId: 'op-alpine-1',
      provider: 'Allianz Aviation Insurance',
      policyNumber: 'AV-2024-78901-IT',
      holderName: 'Alpine Drones SRL',
      issueDate: agoDate(250),
      expiryDate: aheadDate(110),
      notes: 'Flotta aziendale',
      pdfUrl: '',
      verificationStatus: 'verified',
      createdAt: ago(250),
      updatedAt: ago(20),
      dataLockedAt: ago(240),
    },
    {
      id: 'ins-anna-1',
      userId: 'demo-anna',
      link: 'drone',
      droneId: 'drn-anna-1',
      droneIds: ['drn-anna-1'],
      operatorId: null,
      provider: 'HDI Versicherung',
      policyNumber: 'HDI-UAS-2024-553',
      holderName: 'Anna Müller',
      issueDate: agoDate(340),
      expiryDate: aheadDate(12),
      notes: 'In scadenza — rinnovo in corso',
      pdfUrl: '/demo/sample-doc.pdf',
      verificationStatus: 'pending',
      createdAt: ago(340),
      updatedAt: ago(2),
      dataLockedAt: ago(330),
    },
    {
      id: 'ins-carlos-1',
      userId: 'demo-carlos',
      link: 'drone',
      droneId: 'drn-carlos-1',
      droneIds: ['drn-carlos-1'],
      operatorId: null,
      provider: 'Mapfre Seguros',
      policyNumber: 'MPF-UAS-2023-1120',
      holderName: 'Carlos García',
      issueDate: agoDate(400),
      expiryDate: agoDate(15),
      notes: 'SCADUTA — operatore avvisato',
      pdfUrl: '',
      verificationStatus: 'verified',
      createdAt: ago(400),
      updatedAt: ago(8),
      dataLockedAt: ago(390),
    },
  ];

  const certificates: Certificate[] = [
    {
      id: 'cert-michele-1',
      userId: 'demo-michele',
      kind: 'A2',
      label: 'Certificato di competenza A2',
      registrationNumber: MICHELE.operatorLicense,
      issuedBy: 'ENAC',
      issuedAt: agoDate(1800),
      expiresAt: '2026-10-25',
      fileUrl: '',
      verificationStatus: 'verified',
      notes: 'Profilo reale 360° Drone',
      createdAt: ago(200),
      updatedAt: ago(20),
      dataLockedAt: ago(190),
    },
    {
      id: 'cert-michele-2',
      userId: 'demo-michele',
      kind: 'STS_01',
      label: 'Attestato pratico STS-01',
      registrationNumber: 'ITA-STS01-000001023',
      issuedBy: 'ENAC',
      issuedAt: '2024-12-29',
      expiresAt: aheadDate(200),
      fileUrl: '',
      verificationStatus: 'verified',
      notes: 'Training Coordinator: Marco Rapolla',
      createdAt: ago(180),
      updatedAt: ago(18),
      dataLockedAt: ago(170),
    },
    {
      id: 'cert-alpine-1',
      userId: 'demo-alpine',
      kind: 'STS_02',
      label: 'STS-02',
      registrationNumber: 'IT-STS02-2023-1100',
      issuedBy: 'ENAC',
      issuedAt: agoDate(500),
      expiresAt: aheadDate(300),
      fileUrl: '',
      verificationStatus: 'verified',
      notes: '',
      createdAt: ago(200),
      updatedAt: ago(30),
      dataLockedAt: ago(190),
    },
    {
      id: 'cert-anna-1',
      userId: 'demo-anna',
      kind: 'A2',
      label: 'A2 (DE)',
      registrationNumber: 'DE-A2-2024-8834',
      issuedBy: 'LBA',
      issuedAt: agoDate(120),
      expiresAt: aheadDate(600),
      fileUrl: '/demo/sample-doc.pdf',
      verificationStatus: 'pending',
      notes: 'In coda verifica admin',
      createdAt: ago(30),
      updatedAt: ago(1),
      dataLockedAt: ago(28),
    },
    {
      id: 'cert-carlos-1',
      userId: 'demo-carlos',
      kind: 'STS_THEORETICAL',
      label: 'STS teorico',
      registrationNumber: 'ES-STS-2023-7712',
      issuedBy: 'AESA',
      issuedAt: agoDate(700),
      expiresAt: aheadDate(50),
      fileUrl: '',
      verificationStatus: 'verified',
      notes: '',
      createdAt: ago(160),
      updatedAt: ago(40),
      dataLockedAt: ago(150),
    },
    {
      id: 'cert-carlos-expired',
      userId: 'demo-carlos',
      kind: 'A1_A3',
      label: 'A1/A3 (scaduto)',
      registrationNumber: 'ES-A1A3-2020-1102',
      issuedBy: 'AESA',
      issuedAt: agoDate(1200),
      expiresAt: agoDate(30),
      fileUrl: '',
      verificationStatus: 'verified',
      notes: 'In archivio — rinnovare',
      createdAt: ago(400),
      updatedAt: ago(30),
      dataLockedAt: ago(390),
    },
  ];

  const documents: DocumentRef[] = [
    {
      id: 'doc-michele-1',
      userId: 'demo-michele',
      kind: 'drone_registration',
      label: 'Registrazione UAS MiniScout',
      fileUrl: '',
      fileName: 'uas-miniscout.pdf',
      fileSize: 248000,
      mimeType: 'application/pdf',
      verificationStatus: 'verified',
      notes: '',
      createdAt: ago(100),
      updatedAt: ago(100),
    },
    {
      id: 'doc-anna-1',
      userId: 'demo-anna',
      kind: 'training_certificate',
      label: 'Corso teorico urbano',
      fileUrl: '/demo/sample-doc.pdf',
      fileName: 'training-anna.pdf',
      fileSize: 320000,
      mimeType: 'application/pdf',
      verificationStatus: 'pending',
      notes: 'Da verificare',
      createdAt: ago(8),
      updatedAt: ago(8),
    },
    {
      id: 'doc-carlos-1',
      userId: 'demo-carlos',
      kind: 'insurance_policy',
      label: 'Polizza scaduta (archivio)',
      fileUrl: '',
      fileName: 'mapfre-expired.pdf',
      fileSize: 410000,
      mimeType: 'application/pdf',
      verificationStatus: 'rejected',
      notes: 'Documento superato dalla nuova polizza (non caricata)',
      createdAt: ago(20),
      updatedAt: ago(10),
    },
  ];

  const authorizations: Authorization[] = [
    {
      id: 'authz-michele-1',
      userId: 'demo-michele',
      kind: 'nullaosta',
      label: 'Nullaosta area CTR Linate',
      issuedBy: 'ENAC',
      area: 'CTR Milano Linate — corridoio est',
      validFrom: agoDate(10),
      validTo: aheadDate(20),
      fileUrl: '/demo/sample-doc.pdf',
      fileName: 'nullaosta-linate.pdf',
      fileSize: 180000,
      mimeType: 'application/pdf',
      verificationStatus: 'verified',
      notes: 'Valido nei giorni lavorativi 08:00–18:00',
      createdAt: ago(10),
      updatedAt: ago(2),
    },
    {
      id: 'authz-michele-2',
      userId: 'demo-michele',
      kind: 'daily',
      label: 'Autorizzazione giornaliera Parco Sempione',
      issuedBy: 'Comune di Milano',
      area: 'Parco Sempione',
      validFrom: aheadDate(3),
      validTo: aheadDate(3),
      fileUrl: '',
      fileName: 'auth-giornaliera.pdf',
      fileSize: 95000,
      mimeType: 'application/pdf',
      verificationStatus: 'pending',
      notes: '',
      createdAt: ago(1),
      updatedAt: ago(1),
    },
    {
      id: 'authz-michele-expired',
      userId: 'demo-michele',
      kind: 'hourly_nullaosta',
      label: 'Nullaosta orario Fiera Milano',
      issuedBy: 'ENAC',
      area: 'Rho Fiera',
      validFrom: agoDate(40),
      validTo: agoDate(35),
      fileUrl: '/demo/sample-doc.pdf',
      fileName: 'nullaosta-fiera-scaduto.pdf',
      fileSize: 210000,
      mimeType: 'application/pdf',
      verificationStatus: 'verified',
      notes: 'Missione conclusa — in archivio',
      createdAt: ago(45),
      updatedAt: ago(35),
    },
    {
      id: 'authz-anna-1',
      userId: 'demo-anna',
      kind: 'temporary',
      label: 'Temporanea zona urbana Monaco',
      issuedBy: 'LBA',
      area: 'München Innenstadt',
      validFrom: agoDate(5),
      validTo: aheadDate(12),
      fileUrl: '/demo/sample-doc.pdf',
      fileName: 'temp-munich.pdf',
      fileSize: 150000,
      mimeType: 'application/pdf',
      verificationStatus: 'pending',
      notes: '',
      createdAt: ago(5),
      updatedAt: ago(5),
    },
    {
      id: 'authz-carlos-expired',
      userId: 'demo-carlos',
      kind: 'nullaosta',
      label: 'Nullaosta costa Barcelona',
      issuedBy: 'AESA',
      area: 'Litoral Barcelonès',
      validFrom: agoDate(90),
      validTo: agoDate(60),
      fileUrl: '',
      fileName: 'nullaosta-bcn.pdf',
      fileSize: 175000,
      mimeType: 'application/pdf',
      verificationStatus: 'verified',
      notes: 'Scaduto',
      createdAt: ago(95),
      updatedAt: ago(60),
    },
  ];

  const drones: Drone[] = [
    drone({
      id: 'drn-michele-1',
      userId: 'demo-michele',
      slug: MICHELE.publicSlug,
      status: 'active',
      visibility: 'public',
      verificationStatus: 'verified',
      manufacturer: 'DJI',
      model: 'Mini 4 Pro',
      classMarking: 'C0',
      droneSerialNumber: '12433u54354565435',
      linkedPilotId: 'demo-michele',
      defaultOperatorId: 'op-michele-1',
      insuranceId: 'ins-michele-1',
      createdAt: ago(110),
      updatedAt: ago(3),
      publishedAt: ago(100),
      lastVerifiedAt: ago(10),
    }),
    drone({
      id: 'drn-michele-2',
      userId: 'demo-michele',
      slug: 'airmax-360',
      status: 'active',
      visibility: 'public',
      verificationStatus: 'verified',
      manufacturer: 'DJI',
      model: 'Air 3S',
      classMarking: 'C1',
      droneSerialNumber: '1581F84DC24A90012K3M',
      linkedPilotId: 'demo-michele',
      defaultOperatorId: 'op-michele-2',
      activeOperatorId: 'op-michele-1',
      activeOperatorUntil: ahead(8),
      activeOperatorSetAt: ago(1),
      activeOperatorSetBy: 'demo-michele',
      activeOperatorReason: 'Missione weekend privato',
      insuranceId: 'ins-michele-1',
      createdAt: ago(80),
      updatedAt: ago(1),
      publishedAt: ago(70),
      lastVerifiedAt: ago(12),
    }),
    drone({
      id: 'drn-michele-3',
      userId: 'demo-michele',
      slug: 'draft-matrice',
      status: 'draft',
      visibility: 'private',
      verificationStatus: 'unverified',
      manufacturer: 'DJI',
      model: 'Matrice 30T',
      classMarking: 'C3',
      droneSerialNumber: '',
      linkedPilotId: 'demo-michele',
      defaultOperatorId: 'op-michele-2',
      insuranceId: null,
      createdAt: ago(2),
      updatedAt: ago(2),
      publishedAt: '',
      lastVerifiedAt: '',
      dataLockedAt: '',
    }),
    drone({
      id: 'drn-alpine-1',
      userId: 'demo-alpine',
      slug: 'summit-scout',
      status: 'active',
      visibility: 'public',
      verificationStatus: 'verified',
      manufacturer: 'DJI',
      model: 'Matrice 350 RTK',
      classMarking: 'C3',
      droneSerialNumber: '1ZNBJ4M0030A7E',
      linkedPilotId: 'demo-alpine',
      defaultOperatorId: 'op-alpine-1',
      insuranceId: 'ins-alpine-1',
      createdAt: ago(200),
      updatedAt: ago(6),
      publishedAt: ago(190),
      lastVerifiedAt: ago(20),
    }),
    drone({
      id: 'drn-alpine-2',
      userId: 'demo-alpine',
      slug: 'alpine-mavic',
      status: 'active',
      visibility: 'public',
      verificationStatus: 'verified',
      manufacturer: 'DJI',
      model: 'Mavic 3 Enterprise',
      classMarking: 'C2',
      droneSerialNumber: '1581F6G8C243E00ZZ91',
      linkedPilotId: 'demo-alpine',
      defaultOperatorId: 'op-alpine-1',
      activeOperatorId: 'op-alpine-2',
      activeOperatorUntil: ahead(20),
      activeOperatorSetAt: ago(0, 5),
      activeOperatorSetBy: 'demo-alpine',
      activeOperatorReason: 'Turno pilota ospite',
      insuranceId: 'ins-alpine-1',
      createdAt: ago(120),
      updatedAt: ago(0, 5),
      publishedAt: ago(110),
      lastVerifiedAt: ago(25),
    }),
    drone({
      id: 'drn-anna-1',
      userId: 'demo-anna',
      slug: 'citymapper-anna',
      status: 'active',
      visibility: 'public',
      verificationStatus: 'pending',
      manufacturer: 'Autel',
      model: 'EVO II Pro',
      classMarking: 'C2',
      droneSerialNumber: 'AU7K22B003421',
      linkedPilotId: 'demo-anna',
      defaultOperatorId: 'op-anna-1',
      insuranceId: 'ins-anna-1',
      createdAt: ago(40),
      updatedAt: ago(1),
      publishedAt: ago(35),
      lastVerifiedAt: '',
    }),
    drone({
      id: 'drn-pierre-1',
      userId: 'demo-pierre',
      slug: 'pierre-agras-draft',
      status: 'draft',
      visibility: 'private',
      verificationStatus: 'unverified',
      manufacturer: 'DJI',
      model: 'Agras T40',
      classMarking: 'unknown',
      droneSerialNumber: '',
      linkedPilotId: 'demo-pierre',
      defaultOperatorId: 'op-pierre-1',
      insuranceId: null,
      createdAt: ago(2),
      updatedAt: ago(2),
      publishedAt: '',
      lastVerifiedAt: '',
      dataLockedAt: '',
    }),
    drone({
      id: 'drn-carlos-1',
      userId: 'demo-carlos',
      slug: 'vistaone-carlos',
      status: 'active',
      visibility: 'public',
      verificationStatus: 'verified',
      manufacturer: 'DJI',
      model: 'Inspire 3',
      classMarking: 'C3',
      droneSerialNumber: 'INS3A1002Z9',
      linkedPilotId: 'demo-carlos',
      defaultOperatorId: 'op-carlos-1',
      insuranceId: 'ins-carlos-1',
      createdAt: ago(160),
      updatedAt: ago(8),
      publishedAt: ago(150),
      lastVerifiedAt: ago(60),
    }),
    drone({
      id: 'drn-carlos-2',
      userId: 'demo-carlos',
      slug: 'vista-suspended',
      status: 'suspended',
      visibility: 'private',
      verificationStatus: 'verified',
      manufacturer: 'DJI',
      model: 'Air 2S',
      classMarking: 'C1',
      droneSerialNumber: '3YTAK4R001A2B3',
      linkedPilotId: 'demo-carlos',
      defaultOperatorId: 'op-carlos-1',
      insuranceId: null,
      createdAt: ago(100),
      updatedAt: ago(9),
      publishedAt: ago(90),
      lastVerifiedAt: ago(70),
    }),
  ];

  const slots: Omit<Slots, never>[] = [
    {
      userId: 'demo-admin',
      certificate: 0,
      drone: 0,
      operator: 0,
      pdf: 0,
      permit: 0,
      archive: 0,
      nfc_badge: 0,
      personalization: 0,
      createdAt: ago(365),
      updatedAt: ago(5),
    },
    {
      userId: 'demo-michele',
      certificate: 5,
      drone: 5,
      operator: 3,
      pdf: 10,
      permit: 5,
      archive: 0,
      nfc_badge: 8,
      personalization: 2,
      createdAt: ago(120),
      updatedAt: ago(5),
    },
    {
      userId: 'demo-alpine',
      certificate: 4,
      drone: 6,
      operator: 3,
      pdf: 12,
      permit: 5,
      archive: 0,
      nfc_badge: 4,
      personalization: 1,
      createdAt: ago(210),
      updatedAt: ago(15),
    },
    {
      userId: 'demo-anna',
      certificate: 1,
      drone: 1,
      operator: 1,
      pdf: 2,
      permit: 5,
      archive: 0,
      nfc_badge: 0,
      personalization: 0,
      createdAt: ago(45),
      updatedAt: ago(45),
    },
    {
      userId: 'demo-pierre',
      certificate: 1,
      drone: 1,
      operator: 1,
      pdf: 1,
      permit: 5,
      archive: 0,
      nfc_badge: 0,
      personalization: 0,
      createdAt: ago(3),
      updatedAt: ago(3),
    },
    {
      userId: 'demo-carlos',
      certificate: 2,
      drone: 3,
      operator: 2,
      pdf: 4,
      permit: 5,
      archive: 0,
      nfc_badge: 2,
      personalization: 0,
      createdAt: ago(180),
      updatedAt: ago(20),
    },
  ];

  const plans: Plan[] = [
    {
      id: 'plan-drone',
      slotKind: 'drone',
      priceCents: 1900,
      currency: 'CHF',
      active: true,
      label: 'Slot drone extra',
      description: 'Aggiunge 1 drone al piano',
      createdAt: ago(300),
      updatedAt: ago(30),
    },
    {
      id: 'plan-certificate',
      slotKind: 'certificate',
      priceCents: 900,
      currency: 'CHF',
      active: true,
      label: 'Slot certificato',
      description: 'Aggiunge 1 certificato',
      createdAt: ago(300),
      updatedAt: ago(30),
    },
    {
      id: 'plan-nfc',
      slotKind: 'nfc_badge',
      priceCents: 2900,
      currency: 'CHF',
      active: true,
      label: 'Badge NFC',
      description: 'Tessera fisica con NFC + QR',
      createdAt: ago(300),
      updatedAt: ago(10),
    },
    {
      id: 'plan-operator',
      slotKind: 'operator',
      priceCents: 1500,
      currency: 'CHF',
      active: true,
      label: 'Operatore extra',
      description: 'Fino a 3 operatori per account',
      createdAt: ago(300),
      updatedAt: ago(30),
    },
    {
      id: 'plan-permit',
      slotKind: 'permit',
      priceCents: 700,
      currency: 'CHF',
      active: true,
      label: 'Slot autorizzazione',
      description: 'Aggiunge 1 slot per permessi / nullaosta attivi',
      createdAt: ago(300),
      updatedAt: ago(5),
    },
    {
      id: 'plan-archive',
      slotKind: 'archive',
      priceCents: 1200,
      currency: 'CHF',
      active: true,
      label: 'Archivio +30 MB',
      description: 'Espande lo spazio archivio documenti scaduti di 30 MB',
      createdAt: ago(300),
      updatedAt: ago(5),
    },
    {
      id: 'plan-pdf-inactive',
      slotKind: 'pdf',
      priceCents: 500,
      currency: 'CHF',
      active: false,
      label: 'PDF pack (disattivo)',
      description: 'Piano legacy non più in vendita',
      createdAt: ago(400),
      updatedAt: ago(60),
    },
  ];

  const reports: Report[] = [
    {
      id: 'rep-carlos-1',
      droneId: 'drn-carlos-1',
      droneSlug: 'vistaone-carlos',
      ownerUserId: 'demo-carlos',
      finderName: 'Elena Ruiz',
      message: 'Ho trovato un drone vicino al Retiro. Sembra integro, batteria ancora montata.',
      location: { lat: 40.4153, lng: -3.684, accuracy: 12 },
      locationText: 'Parque del Retiro, Madrid',
      contactEmail: 'elena.ruiz@example.com',
      read: false,
      emailNotified: true,
      pushNotified: false,
      createdAt: ago(1, 4),
    },
    {
      id: 'rep-carlos-2',
      droneId: 'drn-carlos-1',
      droneSlug: 'vistaone-carlos',
      ownerUserId: 'demo-carlos',
      finderName: '',
      message: 'Segnalazione precedente: drone visto a terra in Calle Alcalá. Non più sul posto.',
      location: null,
      locationText: 'Calle Alcalá, Madrid',
      contactEmail: '',
      read: false,
      emailNotified: false,
      pushNotified: false,
      createdAt: ago(2, 10),
    },
    {
      id: 'rep-michele-1',
      droneId: 'drn-michele-1',
      droneSlug: MICHELE.publicSlug,
      ownerUserId: 'demo-michele',
      finderName: 'Marco Verdi',
      message: 'Drone recuperato su una spiaggia a Bonassola. Contattatemi per il ritiro.',
      location: { lat: 44.183, lng: 9.584, accuracy: 25 },
      locationText: 'Bonassola (SP)',
      contactEmail: 'marco.verdi@example.it',
      read: true,
      emailNotified: true,
      pushNotified: false,
      createdAt: ago(12),
    },
  ];

  const publics: DronePublicSnapshot[] = [
    publicSnap({
      slug: MICHELE.publicSlug,
      droneId: 'drn-michele-1',
      verificationStatus: 'verified',
      lastVerifiedAt: ago(10),
      publishedAt: ago(100),
      holderKind: 'operator-private',
      holderDisplayName: 'Michele Caffagni',
      manufacturer: 'DJI',
      model: 'Mini 4 Pro',
      classMarking: 'C0',
      droneSerialNumber: '12433u54354565435',
      insuranceStatus: 'valid',
      insuranceProvider: MICHELE.insuranceProvider,
      insuranceValidUntil: MICHELE.insuranceExpiryDate,
      insuranceMaskedPolicyNumber: 'CDA********EUR',
      insurancePdfUrl: MICHELE.insurancePdfUrl,
      profilePhotoUrl: MICHELE.profilePhotoUrl,
      logoUrl: MICHELE.logoUrl,
      bannerUrl: MICHELE.bannerUrl,
      updatedAt: ago(3),
    }),
    publicSnap({
      slug: 'airmax-360',
      droneId: 'drn-michele-2',
      verificationStatus: 'verified',
      lastVerifiedAt: ago(12),
      publishedAt: ago(70),
      holderKind: 'operator-private',
      holderDisplayName: 'Michele Caffagni',
      manufacturer: 'DJI',
      model: 'Air 3S',
      classMarking: 'C1',
      droneSerialNumber: '1581F84DC24A90012K3M',
      insuranceStatus: 'valid',
      insuranceProvider: MICHELE.insuranceProvider,
      insuranceValidUntil: MICHELE.insuranceExpiryDate,
      insuranceMaskedPolicyNumber: 'CDA********EUR',
      insurancePdfUrl: MICHELE.insurancePdfUrl,
      profilePhotoUrl: MICHELE.profilePhotoUrl,
      logoUrl: MICHELE.logoUrl,
      bannerUrl: MICHELE.bannerUrl,
      updatedAt: ago(1),
    }),
    publicSnap({
      slug: 'summit-scout',
      droneId: 'drn-alpine-1',
      verificationStatus: 'verified',
      lastVerifiedAt: ago(20),
      publishedAt: ago(190),
      holderKind: 'operator-company',
      holderDisplayName: 'Alpine Drones SRL',
      manufacturer: 'DJI',
      model: 'Matrice 350 RTK',
      classMarking: 'C3',
      droneSerialNumber: '1ZNBJ4M0030A7E',
      insuranceStatus: 'valid',
      insuranceProvider: 'Allianz Aviation Insurance',
      insuranceValidUntil: aheadDate(110),
      insuranceMaskedPolicyNumber: 'AV-*****-IT',
      insurancePdfUrl: '',
      profilePhotoUrl: DEMO_BRANDING.alpine.profilePhotoUrl,
      logoUrl: DEMO_BRANDING.alpine.logoUrl,
      bannerUrl: DEMO_BRANDING.alpine.bannerUrl,
      updatedAt: ago(6),
    }),
    publicSnap({
      slug: 'alpine-mavic',
      droneId: 'drn-alpine-2',
      verificationStatus: 'verified',
      lastVerifiedAt: ago(25),
      publishedAt: ago(110),
      holderKind: 'operator-private',
      holderDisplayName: 'Sara Negri',
      manufacturer: 'DJI',
      model: 'Mavic 3 Enterprise',
      classMarking: 'C2',
      droneSerialNumber: '1581F6G8C243E00ZZ91',
      insuranceStatus: 'valid',
      insuranceProvider: 'Allianz Aviation Insurance',
      insuranceValidUntil: aheadDate(110),
      insuranceMaskedPolicyNumber: 'AV-*****-IT',
      insurancePdfUrl: '',
      profilePhotoUrl: DEMO_BRANDING.alpine.profilePhotoUrl,
      logoUrl: DEMO_BRANDING.alpine.logoUrl,
      bannerUrl: DEMO_BRANDING.alpine.bannerUrl,
      updatedAt: ago(0, 5),
    }),
    publicSnap({
      slug: 'citymapper-anna',
      droneId: 'drn-anna-1',
      verificationStatus: 'pending',
      lastVerifiedAt: '',
      publishedAt: ago(35),
      holderKind: 'operator-company',
      holderDisplayName: 'SkyMap GmbH',
      manufacturer: 'Autel',
      model: 'EVO II Pro',
      classMarking: 'C2',
      droneSerialNumber: 'AU7K22B003421',
      insuranceStatus: 'expiring',
      insuranceProvider: 'HDI Versicherung',
      insuranceValidUntil: aheadDate(12),
      insuranceMaskedPolicyNumber: 'HDI-*****-553',
      insurancePdfUrl: '',
      profilePhotoUrl: DEMO_BRANDING.anna.profilePhotoUrl,
      logoUrl: DEMO_BRANDING.anna.logoUrl,
      bannerUrl: DEMO_BRANDING.anna.bannerUrl,
      updatedAt: ago(1),
    }),
    publicSnap({
      slug: 'vistaone-carlos',
      droneId: 'drn-carlos-1',
      verificationStatus: 'verified',
      lastVerifiedAt: ago(60),
      publishedAt: ago(150),
      holderKind: 'operator-company',
      holderDisplayName: 'DroneVista S.L.',
      manufacturer: 'DJI',
      model: 'Inspire 3',
      classMarking: 'C3',
      droneSerialNumber: 'INS3A1002Z9',
      insuranceStatus: 'expired',
      insuranceProvider: 'Mapfre Seguros',
      insuranceValidUntil: agoDate(15),
      insuranceMaskedPolicyNumber: 'MPF-*****-120',
      insurancePdfUrl: '',
      profilePhotoUrl: DEMO_BRANDING.carlos.profilePhotoUrl,
      logoUrl: DEMO_BRANDING.carlos.logoUrl,
      bannerUrl: DEMO_BRANDING.carlos.bannerUrl,
      updatedAt: ago(8),
    }),
  ];

  const supportThreads: SupportThread[] = [
    {
      userId: 'demo-anna',
      subject: 'Richiesta cambio nome',
      status: 'open',
      lastMessageAt: ago(0, 3),
      lastMessagePreview: 'Potete correggere il mio cognome in Mueller (senza ü)? Grazie.',
      userUnreadCount: 0,
      adminUnreadCount: 1,
      createdAt: ago(1),
      updatedAt: ago(0, 3),
    },
    {
      userId: 'demo-carlos',
      subject: 'Assicurazione scaduta',
      status: 'open',
      lastMessageAt: ago(1),
      lastMessagePreview: 'Ciao Carlos, carica la nuova polizza e avvisaci — la verifichiamo subito.',
      userUnreadCount: 1,
      adminUnreadCount: 0,
      createdAt: ago(2),
      updatedAt: ago(1),
    },
  ];

  const supportMessages: SupportMessage[] = [
    {
      id: 'smsg-anna-1',
      threadId: 'demo-anna',
      sender: 'user',
      senderUid: 'demo-anna',
      body: 'Buongiorno, sul profilo risulta “Müller” ma sul documento ufficiale è “Mueller”. Potete correggere il cognome? Non posso modificarlo da sola.',
      createdAt: ago(1),
      readByUser: true,
      readByAdmin: true,
    },
    {
      id: 'smsg-anna-2',
      threadId: 'demo-anna',
      sender: 'user',
      senderUid: 'demo-anna',
      body: 'Potete correggere il mio cognome in Mueller (senza ü)? Grazie.',
      createdAt: ago(0, 3),
      readByUser: true,
      readByAdmin: false,
    },
    {
      id: 'smsg-carlos-1',
      threadId: 'demo-carlos',
      sender: 'user',
      senderUid: 'demo-carlos',
      body: 'La polizza Mapfre è scaduta. Come posso aggiornare i dati sul profilo pubblico?',
      createdAt: ago(2),
      readByUser: true,
      readByAdmin: true,
    },
    {
      id: 'smsg-carlos-2',
      threadId: 'demo-carlos',
      sender: 'admin',
      senderUid: 'demo-admin',
      body: 'Ciao Carlos, carica la nuova polizza e avvisaci — la verifichiamo subito.',
      createdAt: ago(1),
      readByUser: false,
      readByAdmin: true,
    },
  ];

  
  return {
    pilots,
    operators,
    insurances,
    certificates,
    documents,
    authorizations,
    drones,
    slots,
    plans,
    reports,
    publics,
    supportThreads,
    supportMessages,
  };
}
